/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/7v1-F1WQc8tIbw7M/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#f0f2f7']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['Cube Material']}
            castShadow
            receiveShadow
            position={[-187.49, 12.12, -485.8]}
          />
          <mesh
            name="Shape"
            geometry={nodes.Shape.geometry}
            material={materials['Shape Material']}
            castShadow
            receiveShadow
            position={[5, 1, 143.25]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <group name="OrangeDude" position={[294.6, -156.21, -319.97]} scale={1.22}>
            <group name="Wizard Hat" position={[0.15, 168.39, -20.7]} rotation={[-0.14, 0, 0]} scale={1.37}>
              <mesh
                name="Torus"
                geometry={nodes.Torus.geometry}
                material={materials['Torus Material']}
                castShadow
                receiveShadow
                position={[0.25, -12.17, 0.08]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1.37, 1.68, 1]}
              />
              <mesh
                name="Merged Geometry"
                geometry={nodes['Merged Geometry'].geometry}
                material={materials.Wizard}
                castShadow
                receiveShadow
                position={[0, 0.02, 0]}
              />
            </group>
            <mesh
              name="Right leg"
              geometry={nodes['Right leg'].geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[24.73, -46.71, -13.76]}
              rotation={[0, 0, 0.17]}
            />
            <mesh
              name="Left Leg"
              geometry={nodes['Left Leg'].geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[-23.95, -45.25, -12.57]}
              rotation={[0, 0, -0.17]}
            />
            <mesh
              name="Cloak Left Arm"
              geometry={nodes['Cloak Left Arm'].geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[-49.81, 9.71, 15.89]}
              rotation={[0, Math.PI / 6, 0]}
              scale={1}
            />
            <mesh
              name="Left Arm"
              geometry={nodes['Left Arm'].geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[-48.86, 15.5, 15.34]}
              rotation={[0, Math.PI / 6, 0]}
              scale={1}
            />
            <mesh
              name="Cloak Right Arm"
              geometry={nodes['Cloak Right Arm'].geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[52.9, 10.81, 15.78]}
              rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Right Arm"
              geometry={nodes['Right Arm'].geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[52.14, 15.5, 15.34]}
              rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Cloak"
              geometry={nodes.Cloak.geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[0, 10.04, -10.98]}
              scale={[1.68, 1.93, 1.34]}
            />
            <mesh
              name="Body"
              geometry={nodes.Body.geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[0, 10.72, -10.98]}
              scale={[1.68, 1.93, 1.34]}
            />
            <group name="Right freckles" position={[38.01, 90.13, 39.9]} rotation={[0, 0, Math.PI / 2]}>
              <mesh
                name="Ellipse 3"
                geometry={nodes['Ellipse 3'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[2.27, -1.11, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse 2"
                geometry={nodes['Ellipse 2'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-2.27, -2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse"
                geometry={nodes.Ellipse.geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-1.86, 2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
            </group>
            <group name="Left freckles" position={[-39.97, 90.13, 39.9]}>
              <mesh
                name="Ellipse 31"
                geometry={nodes['Ellipse 31'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[2.27, -1.11, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse 21"
                geometry={nodes['Ellipse 21'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-2.27, -2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse1"
                geometry={nodes.Ellipse1.geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-1.86, 2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
            </group>
            <group name="Face" position={[-0.35, 95.07, 54.74]}>
              <mesh
                name="Sphere 2"
                geometry={nodes['Sphere 2'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[15.18, 14.79, -10.1]}
              />
              <mesh
                name="Sphere 3"
                geometry={nodes['Sphere 3'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-14.59, 14.79, -10.1]}
              />
              <mesh
                name="Path 2"
                geometry={nodes['Path 2'].geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[0, -0.26, 0.12]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <mesh
                name="Path"
                geometry={nodes.Path.geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[0, -0.26, 0.12]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials.OrangeDudeEyes}
                castShadow
                receiveShadow
                position={[-0.36, 2.98, 0]}
                scale={[1.59, 0.87, 1]}
              />
            </group>
            <mesh
              name="Head"
              geometry={nodes.Head.geometry}
              material={materials.OrangeDude}
              castShadow
              receiveShadow
              position={[-0.82, 100.56, -4.57]}
            />
          </group>
          <group name="Blue" position={[98.4, -156.21, -319.97]} scale={1.22}>
            <group name="Wizard Hat1" position={[0.15, 167.75, -20.61]} rotation={[-0.14, 0, 0]} scale={1.37}>
              <mesh
                name="Torus1"
                geometry={nodes.Torus1.geometry}
                material={materials['Torus1 Material']}
                castShadow
                receiveShadow
                position={[0.25, -12.17, 0.08]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1.37, 1.68, 1]}
              />
              <mesh
                name="Merged Geometry1"
                geometry={nodes['Merged Geometry1'].geometry}
                material={materials.Wizard}
                castShadow
                receiveShadow
                position={[0, 0.02, 0]}
              />
            </group>
            <mesh
              name="Right leg1"
              geometry={nodes['Right leg1'].geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[24.73, -46.71, -13.76]}
              rotation={[0, 0, 0.17]}
            />
            <mesh
              name="Left Leg1"
              geometry={nodes['Left Leg1'].geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[-23.95, -45.25, -12.57]}
              rotation={[0, 0, -0.17]}
            />
            <mesh
              name="Cloak Left Arm1"
              geometry={nodes['Cloak Left Arm1'].geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[-49.81, 9.71, 15.89]}
              rotation={[0, Math.PI / 6, 0]}
              scale={1}
            />
            <mesh
              name="Left Arm1"
              geometry={nodes['Left Arm1'].geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[-48.86, 15.5, 15.34]}
              rotation={[0, Math.PI / 6, 0]}
              scale={1}
            />
            <mesh
              name="Cloak Right Arm1"
              geometry={nodes['Cloak Right Arm1'].geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[52.9, 10.81, 15.78]}
              rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Right Arm1"
              geometry={nodes['Right Arm1'].geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[52.14, 15.5, 15.34]}
              rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Cloak1"
              geometry={nodes.Cloak1.geometry}
              material={materials.Wizard}
              castShadow
              receiveShadow
              position={[0, 10.04, -10.98]}
              scale={[1.68, 1.93, 1.34]}
            />
            <mesh
              name="Body1"
              geometry={nodes.Body1.geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[0, 10.72, -10.98]}
              scale={[1.68, 1.93, 1.34]}
            />
            <group name="Right freckles1" position={[38.01, 90.13, 39.9]} rotation={[0, 0, Math.PI / 2]}>
              <mesh
                name="Ellipse 32"
                geometry={nodes['Ellipse 32'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[2.27, -1.11, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse 22"
                geometry={nodes['Ellipse 22'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-2.27, -2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse2"
                geometry={nodes.Ellipse2.geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-1.86, 2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
            </group>
            <group name="Left freckles1" position={[-39.97, 90.13, 39.9]}>
              <mesh
                name="Ellipse 33"
                geometry={nodes['Ellipse 33'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[2.27, -1.11, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse 23"
                geometry={nodes['Ellipse 23'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-2.27, -2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
              <mesh
                name="Ellipse3"
                geometry={nodes.Ellipse3.geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-1.86, 2.35, 0]}
                rotation={[0, 0, 0.75]}
              />
            </group>
            <group name="Face1" position={[-0.35, 95.07, 54.74]}>
              <mesh
                name="Sphere 21"
                geometry={nodes['Sphere 21'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[15.18, 14.79, -10.1]}
              />
              <mesh
                name="Sphere 31"
                geometry={nodes['Sphere 31'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-14.59, 14.79, -10.1]}
              />
              <mesh
                name="Path 21"
                geometry={nodes['Path 21'].geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[0, -0.26, 0.12]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <mesh
                name="Path1"
                geometry={nodes.Path1.geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[0, -0.26, 0.12]}
              />
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials.BlueDudeEyes}
                castShadow
                receiveShadow
                position={[-0.36, 2.98, 0]}
                scale={[1.59, 0.87, 1]}
              />
            </group>
            <mesh
              name="Head1"
              geometry={nodes.Head1.geometry}
              material={materials.BlueDude}
              castShadow
              receiveShadow
              position={[-0.82, 100.56, -4.57]}
            />
          </group>
          <group name="podium" position={[193.6, -140.21, -164.75]} scale={0.74}>
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials['Cube3 Material']}
              castShadow
              receiveShadow
              position={[0.15, 45.13, 68.42]}
              rotation={[0, 0, 0]}
              scale={[3.19, 0.19, 0.04]}
            />
            <group name="Mic 2" position={[69.94, 78.86, -15.58]} rotation={[0, 0.64, 0]} scale={1}>
              <mesh
                name="Cube 4"
                geometry={nodes['Cube 4'].geometry}
                material={materials['Cube 4 Material']}
                castShadow
                receiveShadow
                position={[7.36, 37.46, 3.47]}
                rotation={[0, 0, 0.68]}
                scale={[0.71, 0.89, 0.4]}
              />
              <mesh
                name="Path2"
                geometry={nodes.Path2.geometry}
                material={materials['Path2 Material']}
                castShadow
                receiveShadow
                position={[-14.6, -53.08, 4.7]}
              />
            </group>
            <group name="Mic" position={[-72.47, 77.52, -26.41]} rotation={[-Math.PI, 0.65, -Math.PI]}>
              <mesh
                name="Cube 41"
                geometry={nodes['Cube 41'].geometry}
                material={materials['Cube 41 Material']}
                castShadow
                receiveShadow
                position={[7.36, 37.46, 3.47]}
                rotation={[0, 0, 0.68]}
                scale={[0.71, 0.89, 0.4]}
              />
              <mesh
                name="Path3"
                geometry={nodes.Path3.geometry}
                material={materials['Path3 Material']}
                castShadow
                receiveShadow
                position={[-14.6, -53.08, 4.7]}
              />
            </group>
            <mesh
              name="Boolean"
              geometry={nodes.Boolean.geometry}
              material={nodes.Boolean.material}
              castShadow
              receiveShadow
              position={[4.17, 62.48, -16.72]}
              scale={[1, 0.63, 1]}
            />
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials['Cube 42 Material']}
              castShadow
              receiveShadow
              position={[0.23, -164.26, 1.35]}
              scale={[1.66, 0.23, 1.22]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes['Cube 3'].geometry}
              material={materials['Cube 3 Material']}
              castShadow
              receiveShadow
              position={[0.23, -149.54, 1.35]}
              scale={[1.91, 0.26, 1.39]}
            />
            <mesh
              name="Cube 2"
              geometry={nodes['Cube 2'].geometry}
              material={materials['Cube 2 Material']}
              castShadow
              receiveShadow
              position={[0.47, -63.35, 36.05]}
              scale={[1.17, 1, 1]}
            />
          </group>
          <mesh
            name="Path4"
            geometry={nodes.Path4.geometry}
            material={materials['Path4 Material']}
            castShadow
            receiveShadow
            position={[15.75, 8.62, -490.12]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-1, 1, 10.32]}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[17.25, -10.13, -592.02]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />

          {/* ZOOM CHANGED HERE */}
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} zoom={1.45}/>
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
